Add SAPS4HANA ITCM Organizational data connector
ballerina-platform/ballerinax-openapi-connectors pull request #441
Opened 2021-09-16 20:50 UTC by kapilraajP

## Purpose
> Add SAPS4HANA ITCM Organizational data connector

## Automation tests
 - Unit tests 
   > Done
 - Integration tests
   > Done

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
 - Ran FindSecurityBugs plugin and verified report? no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes

## Test environment
> JDK 11, Ballerina Swan Lake Beta3

2021-09-24 08:08 UTC, RolandHewage requested changes
Minor change is requested. Please fix it. Rest is fine.

2021-09-24 09:34 UTC, kapilraajP commented on openapi/saps4hana.itcm.organizationaldata/Ballerina.toml
> +keywords = ["sap", "saps4hana", "organizationaldata", "paid"]
Fixed this

2021-09-24 09:54 UTC, RolandHewage approved these changes

2021-09-29 04:37 UTC, aneeshafedo approved these changes

2021-09-29 04:38 UTC, merged