Add prodpad connector to main branch
ballerina-platform/ballerinax-openapi-connectors pull request #456
Opened 2021-09-27 02:54 UTC by sachinira

## Purpose
> $subject 

## Goals
> $subject

## Approach
> $subject

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
 - Ran FindSecurityBugs plugin and verified report? no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes

## Test environment
> JDK 11
Ballerina SL Beta 3
Ubuntu 20.04
 
## Learning
> https://app.swaggerhub.com/apis-docs/ProdPad/prodpad/1.0#/

2021-09-27 03:58 UTC, Chuhaa requested changes

2021-09-27 03:58 UTC, Chuhaa commented on openapi/prodpad/Module.md
> +* Create a [ProdPad account](https://www.prodpad.com/) account
```suggestion
* Create a [ProdPad account](https://www.prodpad.com/)
```

2021-09-28 00:42 UTC, sachinira commented on openapi/prodpad/Module.md
> +* Create a [ProdPad account](https://www.prodpad.com/) account
Fixed this. Thanks

2021-09-28 02:57 UTC, Chuhaa approved these changes

2021-09-29 06:25 UTC, RolandHewage approved these changes

2021-09-29 06:27 UTC, merged